import React, { useState } from 'react';
import { Database, Link, Server, Scale, ArrowRightLeft } from 'lucide-react';
import './ThaneLevelDashboard.css';

export default function CCTNSIntegration() {
  return (
    <div className="thane-dashboard-container" style={{ width: '100%', maxWidth: '1000px', margin: '0 auto' }}>
      <div className="thane-header">
        <h2 className="thane-title" style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', justifyContent: 'center' }}>
          <Link size={32} color="#3b82f6" />
          System Integration (CCTNS & ICJS)
        </h2>
        <p className="thane-subtitle">How our AI software seamlessly connects with existing government databases.</p>
      </div>

      <div style={{ background: 'var(--card-bg)', borderRadius: '1rem', padding: '2rem', border: '1px solid var(--card-border)', marginTop: '2rem', boxShadow: '0 10px 25px -5px rgba(0,0,0,0.05)' }}>
        
        <div style={{ display: 'flex', flexDirection: 'column', gap: '2rem' }}>
          
          {/* Main Flow Diagram */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--icon-bg)', padding: '2rem', borderRadius: '1rem', border: '1px solid var(--card-border)' }}>
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ background: 'var(--card-bg)', padding: '1rem', borderRadius: '0.5rem', border: '2px solid #3b82f6', color: 'var(--text-main)', fontWeight: 'bold' }}>
                <Server size={32} color="#3b82f6" style={{ margin: '0 auto 0.5rem auto', display: 'block' }}/>
                Our AI Core (New System)
              </div>
            </div>
            
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', alignItems: 'center', color: 'var(--text-muted)' }}>
              <ArrowRightLeft size={32} />
              <div style={{ fontSize: '0.8rem', marginTop: '0.5rem' }}>REST API / SOAP (Encrypted)</div>
            </div>
            
            <div style={{ textAlign: 'center', flex: 1 }}>
              <div style={{ background: 'var(--card-bg)', padding: '1rem', borderRadius: '0.5rem', border: '2px solid #64748b', color: 'var(--text-main)', fontWeight: 'bold' }}>
                <Database size={32} color="#64748b" style={{ margin: '0 auto 0.5rem auto', display: 'block' }}/>
                CCTNS / ICJS (Legacy)
              </div>
            </div>
          </div>

          {/* Details Grid */}
          <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1.5rem' }}>
            <div style={{ border: '1px solid var(--card-border)', padding: '1.5rem', borderRadius: '0.75rem', borderLeft: '4px solid #10b981' }}>
              <h3 style={{ margin: '0 0 1rem 0', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>
                <Database size={20} color="#10b981" /> CCTNS Data Sync
              </h3>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.5', margin: 0 }}>
                Whenever an FIR is generated by our AI via the Voice-to-Text module, it doesn't stay isolated. It automatically converts the JSON output into the specific XML/SOAP format required by the national CCTNS servers and uploads it in real-time.
              </p>
            </div>
            
            <div style={{ border: '1px solid var(--card-border)', padding: '1.5rem', borderRadius: '0.75rem', borderLeft: '4px solid #8b5cf6' }}>
              <h3 style={{ margin: '0 0 1rem 0', display: 'flex', alignItems: 'center', gap: '0.5rem', color: 'var(--text-main)', fontSize: '1.1rem' }}>
                <Scale size={20} color="#8b5cf6" /> ICJS Interoperability
              </h3>
              <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', lineHeight: '1.5', margin: 0 }}>
                Connecting Police, Courts, Prisons, and Forensics. When a forensic report arrives at the lab, our AI parses the PDF, extracts key evidence points, and automatically flags the Investigation Officer on their dashboard, updating the court's view simultaneously.
              </p>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
}
